language: ruby
matrix:
  include:
    - rvm: 2.1
    - rvm: 2.2
    - rvm: 2.3.1
    - rvm: ruby-head
    - rvm: jruby-9.0.1.0
      env: JRUBY_OPTS='--debug'
    - rvm: rbx-2
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
cache: bundler
before_script: bundle update
script:
  - bundle exec rspec
  - bundle exec rubocop
addons:
    code_climate:
        repo_token: 6ae386ea5e3e0f8f3a390e6fb2fd5448bf82205026d3427938c12a4254ed5735
