version: "{build}"

branches:
  only:
    - master

build: off

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle install --retry 3 --clean --path  vendor\bundle

environment:
  matrix:
    - RUBY_VERSION: '23'
    - RUBY_VERSION: '22'
    - RUBY_VERSION: '21'

test_script:
  - ruby -v
  - gem -v
  - bundle -v
  - bundle exec rspec
  - bundle exec rubocop

cache:
  - 'vendor\bundle'
